use_frameworks!

platform :ios, '8.0'

target 'im_module_Example' do
  pod 'im_module', :path => '../'

  target 'im_module_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
